Fixed some minor compilation issues
- Removed Common.h; it's no longer needed
- #include <Windows.h> -> #include <windows.h>
- Fixed error C2664 with SetConsoleCtrlHandler usage (was passing in arguments of incorrect types)